# Pushes all data to branch "amData". This is necessary due to not being able to push large amounts of data at once. Once the data is on github, merge the branches through github's interface. Takes about 20 minutes.

git checkout -b amData
git push --set-upstream origin amData
for i in {1..40}
do
    git add data/VariablePWV/ACT_annual_$((i)).*
    git commit -m "Autogenerated new data commit" -m "Automatically generated commits are necessary to push less data to github at a time. This script (commitAMData.sh) does this by committing each PWV tick seperately."
    git push
done
git add data/ACTPWV/ACT_annual_50.45.err
git commit -m "Autogenerated new data commit" -m "Automatically generated commits are necessary to push less data to github at a time. This script (commitAMData.sh) does this by committing each PWV tick seperately."
git push
git checkout main
git branch -d amData

# Create a pull request and fulfill it from amData to main. Then, delete the branch.
