# Autogenerated by Astropy-affiliated package mapsims's setup.py on 2020-06-23 22:54:29 UTC
from __future__ import unicode_literals
import datetime

version = "2.3.1"
githash = "c539090cc8518d71ad4783dcb1d84021ed38f1c4"


major = 2
minor = 3
bugfix = 1

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2020, 6, 23, 22, 54, 29)
debug = False

astropy_helpers_version = "3.0.2"
